services:
  psql_tweet_app:
    image: postgres:15.2
    container_name: psql_tweet_app
    env_file:
      - .env
    ports:
      - '5432:${POSTGRES_PORT}'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    networks:
      - postgres_network_tweet_app
    volumes:
      - postgre_braga_volumes_svc:/var/lib/postgresql/data

networks:
  postgres_network_tweet_app: {}

volumes:
  postgre_braga_volumes_svc: {}